CREATE TABLE IF NOT EXISTS BUILDINGS(
ID    INTEGER  NOT NULL AUTO_INCREMENT PRIMARY KEY,
BUILDING_NAME VARCHAR(255) NOT NULL,
AREA VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FLOORS(
ID    INTEGER  NOT NULL AUTO_INCREMENT PRIMARY KEY,
FLOOR_NAME VARCHAR(255) NOT NULL,
BUILDING_ID INTEGER,
FOREIGN KEY (BUILDING_ID) REFERENCES BUILDINGS(ID) ON DELETE CASCADE
);